### ISSUE TITLE
Decide if we want to cancel our Dribbble account

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mofo-Design-Handbook#41]
cc @vazquez @flukeout @xmatthewx @sabrinang and @lovegushwa (who I'm not sure is on dribbble?)

Please leave your thoughts here.

**Comment by vazquez** [comment]
I still think it's an avenue for us to be open. 

As an example, during one of my Hour of Design sessions I designed a vector HTC Device. I then decided to open source the device design. I posted it to Dribbble, where the maintainer of [sketchapp.tv](http://sketchapp.tv/) spotted it and asked for permission to post it in [their website](http://browse.sketchapp.tv/post/121507356570/htc-one-mockup). This allowed the design to reach more people, which was my goal.

In order to accurately decide if Dribbble is a viable option, we need to work harder at updating it. My proposal is for us to commit to one shot a week from each of us. This will keep a really nice pace on our page.

Dribbble doesn't need to showcase finished objects. [Show](https://dribbble.com/shots/1280859-Sketch-Monster?list=users&offset=13) some [sketches](https://dribbble.com/shots/1577057--inmysketchbook?list=users&offset=10), [works](https://dribbble.com/shots/1735455-Filer) in [progress](https://dribbble.com/shots/1809044-Filer-2-0?list=users&offset=5), or [something](https://dribbble.com/shots/1847629-Dark-Earth?list=users&offset=4) you're proud of.

**Comment by cassiemc** [comment]
Awesome thoughts and use case @vazquez thanks :) I'm willing to commit to one shot a week.

**Comment by cassiemc** [comment]
I think we have decided. @vazquez had some very good points and I agree we can give it a better shot. Our current subscription expires  2015-09-18 so I will check in on periodically before that point to reassess.

**Comment by cassiemc** [comment]
We are in fact going to cancel this account. Despite our best intentions it was hardly used.
